version: "3.9"

services:

  # ========================
  # SQL Server
  # ========================
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: expense-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  # ========================
  # Backend API
  # ========================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-backend
    ports:
      - "5050:6000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;
        Database=ExpenseTrackerDb;
        User Id=sa;
        Password=YourStrong@Passw0rd;
        TrustServerCertificate=True;
    depends_on:
      - sqlserver
    command: ["sh", "-c", "sleep 10 && dotnet ExpenseTracker.API.dll"]

  # ========================
  # Frontend
  # ========================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense-frontend
    ports:
      - "3002:3002"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:5050"
    depends_on:
      - backend

volumes:
  sqlserver_data: